# do not edit this file. put files in the dir below.

# ensure idempotent bashrc sourcing
# if DEFAULT_PATH not set
if [[ -z "$DEFAULT_PATH" ]] ; then
  # set it!
  export DEFAULT_PATH=$PATH
else
  # reset path to default path for idempotent bashrc sourcing
  export PATH=$DEFAULT_PATH
fi

# load .bashrc if available
[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [ -d "$HOME/Library/profile.d" ]; then
  for FN in $HOME/Library/profile.d/*.sh ; do
    source "$FN"
  done
fi
