# do not edit this file. put files in the dir below.

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [ -d "$HOME/Library/bashrc.d" ]; then
  for FN in $HOME/Library/bashrc.d/*.sh ; do
    source "$FN"
  done
fi
